### ISSUE TITLE
module not found in rule `make_taxonomy_notebook_wc`

### ISSUE THREAD

**Issue by mr-eyes** [dib-lab/genome-grist#110]
genome-grist is failing with the following error message:

```
Activating conda environment: /home/mhussien/placenta/slurm_job/.snakemake/conda/7a909fafb0abae02d0fb5f8868340577

== This is sourmash version 4.2.2. ==
== Please cite Brown and Irber (2016), doi:10.21105/joss.00027. ==

loaded 3 gather results.
of 3, missed 0 lineage assignments.
loaded results from 1 gather CSVs
saving `annotate` output to grist_output/gathertax/S030.x.genbank.gather.with-lineages.csv.
[Sun Aug 22 05:59:38 2021]
Finished job 235.
19 of 169 steps (11%) done
Select jobs to execute...

[Sun Aug 22 05:59:39 2021]
rule make_taxonomy_notebook_wc:
    input: /home/mhussien/genome-grist/genome_grist/conf/../notebooks/report-taxonomy.ipynb, grist_output/gathertax/S030.x.genbank.gather.with-lineages.csv, grist_output/.kernel.set
    output: grist_output/reports/report-taxonomy-S030.ipynb, grist_output/reports/report-taxonomy-S030.html
    jobid: 234
    wildcards: sample=S030
    resources: tmpdir=/tmp

Activating conda environment: /home/mhussien/placenta/slurm_job/.snakemake/conda/12acdf8a89499d9019393ff3b558f2e7
Traceback (most recent call last):
  File "/home/mhussien/placenta/slurm_job/.snakemake/conda/12acdf8a89499d9019393ff3b558f2e7/bin/papermill", line 10, in <module>
    sys.exit(papermill())
  File "/home/mhussien/placenta/slurm_job/.snakemake/conda/12acdf8a89499d9019393ff3b558f2e7/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/mhussien/placenta/slurm_job/.snakemake/conda/12acdf8a89499d9019393ff3b558f2e7/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/mhussien/placenta/slurm_job/.snakemake/conda/12acdf8a89499d9019393ff3b558f2e7/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mhussien/placenta/slurm_job/.snakemake/conda/12acdf8a89499d9019393ff3b558f2e7/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/mhussien/placenta/slurm_job/.snakemake/conda/12acdf8a89499d9019393ff3b558f2e7/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/mhussien/placenta/slurm_job/.snakemake/conda/12acdf8a89499d9019393ff3b558f2e7/lib/python3.9/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/home/mhussien/placenta/slurm_job/.snakemake/conda/12acdf8a89499d9019393ff3b558f2e7/lib/python3.9/site-packages/papermill/execute.py", line 122, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/home/mhussien/placenta/slurm_job/.snakemake/conda/12acdf8a89499d9019393ff3b558f2e7/lib/python3.9/site-packages/papermill/execute.py", line 234, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError:
---------------------------------------------------------------------------
Exception encountered at "In [1]":
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/tmp/ipykernel_80944/3274139821.py in <module>
      5 import glob
      6 from collections import defaultdict
----> 7 from sourmash.lca import lca_utils
      8 from sourmash.lca.lca_utils import LineagePair

ModuleNotFoundError: No module named 'sourmash'
```

full log: `/home/mhussien/placenta/slurm_job/old_log/slurm_placenta_exp.37839188.err`

**Comment by ctb** [comment]
ahh, yes, I think we probably need to add sourmash to that environment. I'll add it to my list ;).

In the meantime, you can do
```
conda activate /home/mhussien/placenta/slurm_job/.snakemake/conda/7a909fafb0abae02d0fb5f8868340577
conda install -y sourmash
```
to do a patch install.

**Comment by mr-eyes** [comment]
Hi, sorry for getting back to this after a while.

I tried activating the conda env with the problem, installing sourmash, tried again and it didn't work. I also tried running jupyter-notebook to reproduce the problem and here is what I am getting.

![image](https://user-images.githubusercontent.com/7165864/133354337-73f11ef2-391f-4f3b-abad-84da5dc2ed4f.png)

I will continue troubleshooting but would appreciate some help :)

**Comment by ctb** [comment]
hmm, so it looks like maybe the notebook isn't using the right kernel, so isn't pointing at the right environment. Odd.

Could you try adding 

```
import sys
sys.executable
```

at the top of `genome_grist/notebooks/report-taxonomy.ipynb`, just before `import glob`?

**Comment by ctb** [comment]
so, I spent some time digging around in your `/home/mhussien/placenta/slurm_job` directory, and I am wondering if you are (...unnecessarily) removing and/or cleaning out the `.snakemake/conda` subdirectory somehow in your job script? The environment referenced above doesn't exist, and the conda install should have worked.

Anyhoo, I'm testing the addition of sourmash to the papermill environment right now; will create a PR for you to test out in a sec.

**Comment by ctb** [comment]
hi @mr-eyes please give https://github.com/dib-lab/genome-grist/pull/111 a try.

**Comment by ctb** [comment]
did #111 work?
