### ISSUE TITLE
can't download gather genomes starting from gather csv file

### ISSUE THREAD

**Issue by taylorreiter** [dib-lab/genome-grist#119]
I'm trying to use a gather csv output generated by another workflow as input to genome-grist, with the goal of downloading those gather matches.

Genome-grist version: 0.7.3
My conf file looks like this:
```
sample:
- gather_gtdb-rs202-genomic
outdir: outputs
metagenome_trim_memory: 1e9
```

I have the gather csv here:
```
outputs/genbank/gather_gtdb-rs202-genomic.x.genbank.gather.csv
```

When I try and run the `download_matching_genomes` target directly, I get this error:

```
$ genome-grist run conf/genome-grist-conf.yml download_matching_genomes
```
```
sample: ['gather_gtdb-rs202-genomic']
outdir: outputs
Building DAG of jobs...
InputFunctionException in line 189 of /home/tereiter/github/2021-metapangenome-example/.snakemake/conda/86762d5f0fa5b4ff96cae083277aef7f/lib/python3.10/site-packages/genome_grist/conf/Snakefile:
Error:
  WorkflowError:
    Missing wildcard values for sample
Wildcards:

Traceback:
  File "/home/tereiter/github/2021-metapangenome-example/.snakemake/conda/86762d5f0fa5b4ff96cae083277aef7f/lib/python3.10/site-packages/genome_grist/conf/Snakefile", line 160, in __call__
Error in snakemake invocation: Command '['snakemake', '-s', '/home/tereiter/github/2021-metapangenome-example/.snakemake/conda/86762d5f0fa5b4ff96cae083277aef7f/lib/python3.10/site-packages/genome_grist/conf/Snakefile', '-j', '1', '--use-conda', 'download_matching_genomes', '--configfile', '/home/tereiter/github/2021-metapangenome-example/.snakemake/conda/86762d5f0fa5b4ff96cae083277aef7f/lib/python3.10/site-packages/genome_grist/conf/defaults.conf', '/home/tereiter/github/2021-metapangenome-example/.snakemake/conda/86762d5f0fa5b4ff96cae083277aef7f/lib/python3.10/site-packages/genome_grist/conf/system.conf', 'conf/genome-grist-conf.yml']' returned non-zero exit status 1.
```

My work around used to be to use the make_sgc_conf target, but I get this error when I do that:
```
$ genome-grist run conf/genome-grist-conf.yml make_sgc_conf
sample: ['gather_gtdb-rs202-genomic']
outdir: outputs
Building DAG of jobs...
MissingInputException in line 214 of /home/tereiter/github/2021-metapangenome-example/.snakemake/conda/86762d5f0fa5b4ff96cae083277aef7f/lib/python3.10/site-packages/genome_grist/conf/Snakefile:
Missing input files for rule make_sgc_conf:
outputs/sgc/gather_gtdb-rs202-genomic.conf
Error in snakemake invocation: Command '['snakemake', '-s', '/home/tereiter/github/2021-metapangenome-example/.snakemake/conda/86762d5f0fa5b4ff96cae083277aef7f/lib/python3.10/site-packages/genome_grist/conf/Snakefile', '-j', '1', '--use-conda', 'make_sgc_conf', '--configfile', '/home/tereiter/github/2021-metapangenome-example/.snakemake/conda/86762d5f0fa5b4ff96cae083277aef7f/lib/python3.10/site-packages/genome_grist/conf/defaults.conf', '/home/tereiter/github/2021-metapangenome-example/.snakemake/conda/86762d5f0fa5b4ff96cae083277aef7f/lib/python3.10/site-packages/genome_grist/conf/system.conf', 'conf/genome-grist-conf.yml']' returned non-zero exit status 1.
```

When I try and run the rules directly, I get this error:
```
$ genome-grist run conf/genome-grist-conf.yml --until download_matching_genome_wc -j 1
sample: ['gather_gtdb-rs202-genomic']
outdir: outputs
Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Traceback (most recent call last):
  File "/home/tereiter/github/2021-metapangenome-example/.snakemake/conda/86762d5f0fa5b4ff96cae083277aef7f/lib/python3.10/site-packages/snakemake/__init__.py", line 699, in snakemake
    success = workflow.execute(
  File "/home/tereiter/github/2021-metapangenome-example/.snakemake/conda/86762d5f0fa5b4ff96cae083277aef7f/lib/python3.10/site-packages/snakemake/workflow.py", line 1039, in execute
    logger.run_info("\n".join(dag.stats()))
  File "/home/tereiter/github/2021-metapangenome-example/.snakemake/conda/86762d5f0fa5b4ff96cae083277aef7f/lib/python3.10/site-packages/snakemake/dag.py", line 2153, in stats
    "min threads": min(min_threads.values()),
ValueError: min() arg is an empty sequence
Error in snakemake invocation: Command '['snakemake', '-s', '/home/tereiter/github/2021-metapangenome-example/.snakemake/conda/86762d5f0fa5b4ff96cae083277aef7f/lib/python3.10/site-packages/genome_grist/conf/Snakefile', '-j', '1', '--use-conda', '--until', 'download_matching_genome_wc', '-j', '1', '--configfile', '/home/tereiter/github/2021-metapangenome-example/.snakemake/conda/86762d5f0fa5b4ff96cae083277aef7f/lib/python3.10/site-packages/genome_grist/conf/defaults.conf', '/home/tereiter/github/2021-metapangenome-example/.snakemake/conda/86762d5f0fa5b4ff96cae083277aef7f/lib/python3.10/site-packages/genome_grist/conf/system.conf', 'conf/genome-grist-conf.yml']' returned non-zero exit status 1.
```

I'm thoroughly confused by these goings ons, and not really sure where to start with the debugging

**Comment by ctb** [comment]
Looking into this - and I think I understand it, but am not sure how cleanly I can explain it :). Fixes incoming!

The basic problem is this: the `download_matching_genomes` target does not provide a sample name.

---

More specifically,

```
rule download_matching_genomes:
    input:
        Checkpoint_GatherResults("genbank_genomes/{acc}_genomic.fna.gz"),
```

doesn't specify a sample wildcard with `{sample}`, and that's why you get the error message `Missing wildcard values for sample`.

The reason why `make_sgc_conf` works is that  the rule provides `sample`, like so:

```
rule make_sgc_conf:
    input:
        expand(f"{outdir}/sgc/{{sample}}.conf", sample=SAMPLES)
```

which then passes through the `create_sgc_conf_wc` rule et voila.

---

Digging into this more, it looks like I the real root of the problem is that I am using the wildcard handling class `Checkpoint_GatherResults` inconsistently. In some places, I do:

```
Checkpoint_GatherResults(outdir + f"/minimap/{{sample}}.x.{{acc}}.consensus.fa.gz")
```

where I request that snakemake fill in both `sample` and `acc`.

In other places, I do:

```
Checkpoint_GatherResults('genbank_genomes/{acc}.info.csv')
```

where I only request `acc`. 

One solution is to split the `Checkpoint_GatherResults` class in two - one that does it for all samples, the other that does it for whichever sample is requested by the passed-in pattern.

A different solution is to adjust the `Checkpoint_GatherResutls` class to automatically do the thing for all samples, if no sample is specified.

Either way, a better error message is called for :)

---

Also, while the error message from trying to run `download_matching_genome_wc` is confusing, all of the _wc rules are wildcard rules and can't be run directly - you need to ask for a specific file output, or run a concrete rule.
