### ISSUE TITLE
genome-grist installation: error at pip install step

### ISSUE THREAD

**Issue by bcpd** [dib-lab/genome-grist#186]
Thank you for developing this awesome tool.

I'm following the installation instructions of the quickstart guide, but ran into the error printed below at the `python -m pip install genome-grist` step. Help greatly appreciated.

```
Collecting genome-grist
  Downloading genome-grist-0.8.3.tar.gz (8.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.9/8.9 MB 13.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [40 lines of output]
      /home/mixtures/miniconda3/envs/grist/lib/python3.9/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f3328904b80>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/pyparsing/
      WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f332890e790>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/pyparsing/
      WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f332890eaf0>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/pyparsing/
      WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f332890ecd0>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/pyparsing/
      WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f332890ee80>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/pyparsing/
      ERROR: Could not find a version that satisfies the requirement pyparsing!=3.0.5,>=2.0.2 (from versions: none)
      ERROR: No matching distribution found for pyparsing!=3.0.5,>=2.0.2
      Traceback (most recent call last):
        File "/home/mixtures/miniconda3/envs/grist/lib/python3.9/site-packages/setuptools/installer.py", line 82, in fetch_build_egg
          subprocess.check_call(cmd)
        File "/home/mixtures/miniconda3/envs/grist/lib/python3.9/subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/home/mixtures/miniconda3/envs/grist/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp7_hpxryo', '--quiet', 'pyparsing!=3.0.5,>=2.0.2']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-6mr06skn/genome-grist_cf62c18714604a0289dc8f34e9220beb/setup.py", line 24, in <module>
          setup(
        File "/home/mixtures/miniconda3/envs/grist/lib/python3.9/site-packages/setuptools/__init__.py", line 86, in setup
          _install_setup_requires(attrs)
        File "/home/mixtures/miniconda3/envs/grist/lib/python3.9/site-packages/setuptools/__init__.py", line 80, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "/home/mixtures/miniconda3/envs/grist/lib/python3.9/site-packages/setuptools/dist.py", line 861, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/home/mixtures/miniconda3/envs/grist/lib/python3.9/site-packages/pkg_resources/__init__.py", line 789, in resolve
          dist = best[req.key] = env.best_match(
        File "/home/mixtures/miniconda3/envs/grist/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1075, in best_match
          return self.obtain(req, installer)
        File "/home/mixtures/miniconda3/envs/grist/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1087, in obtain
          return installer(requirement)
        File "/home/mixtures/miniconda3/envs/grist/lib/python3.9/site-packages/setuptools/dist.py", line 941, in fetch_build_egg
          return fetch_build_egg(self, req)
        File "/home/mixtures/miniconda3/envs/grist/lib/python3.9/site-packages/setuptools/installer.py", line 84, in fetch_build_egg
          raise DistutilsError(str(e)) from e
      distutils.errors.DistutilsError: Command '['/home/mixtures/miniconda3/envs/grist/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp7_hpxryo', '--quiet', 'pyparsing!=3.0.5,>=2.0.2']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by bcpd** [comment]
Thank you for replying so quickly -- I retried it and it indeed fixed itself. Thanks!
