### ISSUE TITLE
Problem with rule extract_leftover_reads_wc (DeprecationWarning: Implementing implicit namespace packages)

### ISSUE THREAD

**Issue by jessicalumian** [dib-lab/genome-grist#268]
Hello! I'm using v0.9.3 I got an error in the `rule extract_leftover_reads_wc` step.

yml:

```
samples:
- ckd_AA_RX_25_31201053301001_LP_550_C1_L2_R128
outdir: outputs.ckd/

sourmash_databases:
- /home/jupyter-jessica/databases/gtdb-rs207.genomic-reps.dna.k31.zip
- /home/jupyter-jessica/databases/genbank-2022.03-fungi-k31.zip
- /home/jupyter-jessica/databases/genbank-2022.03-protozoa-k31.zip
- /home/jupyter-jessica/databases/genbank-2022.03-viral-k31.zip

prevent_sra_download: true
```

run command:

```
genome-grist run <yml> summarize_gather summarize_mapping
```

Error:

```
Activating conda environment: .snakemake/conda/6c290c02b5d5f573be9149ec407ce91a_
Traceback (most recent call last):
  File "/home/jupyter-jessica/git/CKD_microbiome/sandbox/grist_compare/grist/.snakemake/conda/6c290c02b5d5f573be9149ec407ce91a_/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/jupyter-jessica/git/CKD_microbiome/sandbox/grist_compare/grist/.snakemake/conda/6c290c02b5d5f573be9149ec407ce91a_/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jupyter-jessica/git/CKD_microbiome/sandbox/grist_compare/grist/.snakemake/conda/6c290c02b5d5f573be9149ec407ce91a_/lib/python3.9/site-packages/genome_grist/subtract_gather.py", line 2, in <module>
    import screed
  File "/home/jupyter-jessica/git/CKD_microbiome/sandbox/grist_compare/grist/.snakemake/conda/6c290c02b5d5f573be9149ec407ce91a_/lib/python3.9/site-packages/screed/__init__.py", line 39, in <module>
    from pkg_resources import get_distribution, DistributionNotFound
  File "/home/jupyter-jessica/git/CKD_microbiome/sandbox/grist_compare/grist/.snakemake/conda/6c290c02b5d5f573be9149ec407ce91a_/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3257, in <module>
    def _initialize_master_working_set():
  File "/home/jupyter-jessica/git/CKD_microbiome/sandbox/grist_compare/grist/.snakemake/conda/6c290c02b5d5f573be9149ec407ce91a_/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3231, in _call_aside
    f(*args, **kwargs)
  File "/home/jupyter-jessica/git/CKD_microbiome/sandbox/grist_compare/grist/.snakemake/conda/6c290c02b5d5f573be9149ec407ce91a_/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3282, in _initialize_master_working_set
    tuple(dist.activate(replace=False) for dist in working_set)
  File "/home/jupyter-jessica/git/CKD_microbiome/sandbox/grist_compare/grist/.snakemake/conda/6c290c02b5d5f573be9149ec407ce91a_/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3282, in <genexpr>
    tuple(dist.activate(replace=False) for dist in working_set)
  File "/home/jupyter-jessica/git/CKD_microbiome/sandbox/grist_compare/grist/.snakemake/conda/6c290c02b5d5f573be9149ec407ce91a_/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2803, in activate
    declare_namespace(pkg)
  File "/home/jupyter-jessica/git/CKD_microbiome/sandbox/grist_compare/grist/.snakemake/conda/6c290c02b5d5f573be9149ec407ce91a_/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2297, in declare_namespace
    warnings.warn(msg, DeprecationWarning, stacklevel=2)
DeprecationWarning: Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
```

I've been running grist the same way in a different location without this problem. Not sure if this is an install or user error on my part!

**Comment by ctb** [comment]
I think I fixed this in https://github.com/dib-lab/genome-grist/pull/270. Can you test by doing an install from the latest version in source, or should I just release a new version for you?
