### ISSUE TITLE
Problem installing geome-grist & spacegraphcats

### ISSUE THREAD

**Issue by hehouts** [dib-lab/genome-grist#273]
Hi! 👋 
I was going to install genome-grist and spacegraphcats into one conda environment. 
I started by doing a fresh install of genome-grist, and then when I went to install spacegraphcats, I got an error (below).

It's  genome-grist version `v0.9.3` (from `genome-grist info`)
& spacegraphcats version `v2.1.3.dev10+g0ba7e07` (from `spacegraphcats info`, after recloning and installing in a fresh conda environment)

```
Obtaining file:///home/hehouts/spacegraphcats
  Preparing metadata (setup.py) ... done
Collecting screed<2,>=1.1
  Using cached screed-1.1.2-py2.py3-none-any.whl (95 kB)
Collecting pytest
  Using cached pytest-7.2.2-py3-none-any.whl (317 kB)
Requirement already satisfied: numpy in ./miniconda3/envs/grist/lib/python3.9/site-packages (from spacegraphcats==2.1.3.dev10+g0ba7e07) (1.24.2)
Collecting snakemake==7.24.2
  Using cached snakemake-7.24.2-py3-none-any.whl (364 kB)
Collecting sortedcontainers
  Using cached sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Collecting sourmash<5,>=4.6.1
  Using cached sourmash-4.7.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.7 MB)
Collecting khmer
  Using cached khmer-2.1.1.tar.gz (8.5 MB)
  Preparing metadata (setup.py) ... done
Collecting bbhash>=0.5.4
  Using cached bbhash-0.5.4.tar.gz (19 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-bkxaay2p/bbhash_220c059879914f04ac775ba08c77b63f/setup.py", line 3, in <module>
          from Cython.Distutils import build_ext
      ModuleNotFoundError: No module named 'Cython'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

this isn't really causing me any problems, I can just use 2 environments, but still wanted to make a note of it

**Comment by ctb** [comment]
I _think_ this is because of khmer, which is a whole separate problem. But if you want to get it working, you can do `pip install Cython`.

Backing up a bit, it would be good if you could include the whole set of commands you used - from creating the environment, to installing things. thanks :)
